export const data = [
  {
    id: "1",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    id: "2",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "missing",
  },
  {
    id: "3",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    id: "4",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    id: "5",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    id: "6",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    id: "7",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    id: "8",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    id: "9",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    id: "10",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    id: "11",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    id: "12",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    id: "13",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "missing",
  },
  {
    id: "14",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    id: "15",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    id: "16",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "missing",
  },
  {
    id: "17",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    id: "18",
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
];
