export const data = [
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "missing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "missing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "approved",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "missing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
  {
    name: "Lorem ipsum dolor sit ",
    brand: "amet consectetur adi",
    price: 40,
    quantity: 23,
    total: 99,
    status: "urgentlyMissing",
  },
];
